### ISSUE TITLE
Add registration

### ISSUE THREAD

**Issue by Artemmal** [neftsv/eleks-integrnship-dotnet#12]
Add the ability to sign up for every user.

**Comment by IhorPetrunchak** [comment]
Can you please comment if it's ok so far because I'm having a little trouble with it
https://github.com/neftsv/eleks-integrnship-dotnet/pull/16/files#diff-fab5809139fabefdca0d6b5ac1d0ade6cae321840b062d089aad79d86d43bac6

**Comment by IhorPetrunchak** [comment]
Сheck - https://github.com/neftsv/eleks-integrnship-dotnet/pull/20
